name = "FuzzyPatternTM"
uuid = "3f005b0e-9e6c-4f43-9d84-1f8cf4a2d1c2"
version = "0.2.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Random = "9a3f8284-686f-5a3c-9b56-6d3c1b5f7b7a"

[compat]
Flux = "0.14"
JSON3 = "1"
MLDatasets = "0.5.13"
Zygote = "0.6"
